apytypes/apytypes

lib/test/apyfixed/test_methods.py
lib/test/test_floating_point.py
src/apyfixed_wrapper.cc
src/apyfloat_wrapper.cc

Make things properties

---

.gitignore
lib/test/apyfixedarray/test_constructors.py
src/apyfixedarray.cc
src/ieee754.h
src/python_util.h

src: add multi-type support for python_sequence_walk()

---

src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc

This was quite easy for `APyFloat` although one can question how important they are...

Add logic operations for APyFloat

---

lib/apytypes/__init__.py
lib/test/apyfloatarray/test_arithmetic.py
lib/test/apyfloatarray/test_constructors.py
lib/test/apyfloatarray/test_methods.py
lib/test/apyfloatarray/test_representation.py
meson.build
pyproject.toml
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc
src/apytypes_common.h
src/apytypes_wrapper.cc

The following is included in this PR:
* constructor
* `from_float`
* `is_identical`
* transpose
* addition, subtraction, multiplication, and division,
* `to_numpy`
Addition with "0" and multiplication with "1" is also supported.

Initial support for APyFloatArray

---

lib/test/apyfloatarray/test_matmul.py
lib/test/apyfloatarray/test_methods.py
meson.build
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_iterator.cc
src/apyfloatarray_iterator.h
src/apyfloatarray_wrapper.cc

This PR includes
* matrix multiplication (`__matmul__`,
* indexing (`__get_item__`),
* iterator (`__iter__`),
* `__array__`, 
* and resize
for APyFloatArray

More APyFloatArray features

---

lib/apytypes/_apytypes.pyi
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc
src/apyfloatarray.cc
src/apytypes_common.cc
src/apytypes_common.h

src: parameter rename quantization_mode -> quantization

---

lib/test/apyfixed/test_quantization.py
src/apyfixed.cc
src/apyfixed.h
src/apyfixedarray.cc
src/apyfloat.cc
src/apyfloatarray.cc

This PR adds the following quantization modes to APyFixed (and APyFixedArray):
* `JAM_UNBIASED`

src: add APyFixed::_quantize_jam_unbiased()

---

examples/apyfixed.py
examples/apyfloat.py
lib/apytypes/_apytypes.pyi
lib/test/apyfixed/test_quantization.py
lib/test/apyfloat/test_rounding.py
lib/test/apyfloatarray/test_methods.py
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Rename resize to cast and deprecate resize

---

lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloatarray/test_arithmetic.py
pyproject.toml
src/apyfloat.cc
src/apyfloat.h

This PR closes issue #110.
The code should be be cleaned up in the future.

Fixes to ApyFloat arithmetic 

---

src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc

Add convenience methods for casting

---

src/apyfixedarray.cc
src/apytypes_util.h

```Python
from apytypes import APyFixedArray
a = APyFixedArray([range(100), range(100), range(100)], bits=32, int_bits=16)
b = a.T
for _ in range(10000):
c = b @ a
```
Before:
```bash
❯ time py-spy record -o profilemultnoinline.svg --native -- python3 bench_matmul.py
py-spy record -o profilemultnoinline.svg --native -- python3 bench_matmul.py  33,73s user 0,93s system 100% cpu 34,534 total
```
After:
```bash
❯ time py-spy record -o profilemultnoinline.svg --native -- python3 bench_matmul.py
py-spy record -o profilemultnoinline.svg --native -- python3 bench_matmul.py  21,80s user 0,50s system 100% cpu 22,264 total
```
EDIT:
Closes #126

src: `limb_vector_abs` in-place

---

lib/test/apyfixed/test_arithmetic.py
lib/test/apyfixedarray/test_arithmetic.py
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc

Add inline shifting for fixed-point

---

.clangd-gen.py
.github/workflows/run_coverage.yml
apytypes_stubgen.sh
lib/apytypes/__init__.py
lib/test/test_contextmanagers.py
meson.build
pyproject.toml
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_iterator.cc
src/apyfixedarray_iterator.h
src/apyfixedarray_wrapper.cc
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_iterator.cc
src/apyfloatarray_iterator.h
src/apyfloatarray_wrapper.cc
src/apytypes_common.cc
src/apytypes_context_wrapper.cc
src/apytypes_util.h
src/apytypes_wrapper.cc
src/python_util.h
subprojects/nanobind.wrap

nanobind: port project from pybind11 to nanobind

---

lib/test/apyfixedarray/test_constructors.py
src/apyfixedarray.cc
src/apytypes_util.h
src/python_util.h

src: python_sequence_extract_shape, filter strings

---

lib/test/apyfloatarray/test_arithmetic.py
src/apyfloat.cc
src/apyfloat.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Closes #177.
Also specialized array/scalar operations to improve performance (slightly) and to enable later optimizations.

Add unary negation and specialize array/scalar operations

---

lib/test/apyfixed/test_quantization.py
src/apytypes_util.h

src: fix memory out-of-bounds access bug, closes #179

---

lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc

Handle long formats in APyFloat power function

---

lib/test/apyfixedarray/test_constructors.py
lib/test/apyfloatarray/test_constructors.py
src/apyfloat.h
src/apyfloatarray.cc
src/apyfloatarray.h

Specialize conversion of numpy arrays to APyFloatArray

---

.clangd-gen.py
src/apyfloat.cc

Make use of the new dedicated functions in APyFixed.

Accelerate APyFloat::leading_zeros_apyfixed

---

lib/test/apyfixed/test_arithmetic.py
src/apyfixed.cc
src/apytypes_util.h

src: fix bit-mask bug in APyFixed::leading_fractional_zeros()

---

lib/test/apyfloat/test_rounding.py

Tests for quantization in division

---

lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloat/test_methods.py
lib/test/apyfloat/test_rounding.py

Increase the test coverage for floating-point addition and subtraction. If dead code is found it will be removed. Related to #236.

Increase test coverage of floating-point addition/subtraction

---

src/apyfixed.cc
src/apyfixed.h
src/apyfloat.cc

Closes #233 
Can be further improved, but for now it is at least faster for short word lengths.

Add special methods to compare against one and two

---

docs/_plots/quantization.py
docs/api/quantizationoverflow.rst
lib/test/apyfixed/test_quantization.py
lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloat/test_rounding.py
src/apyfixed.cc
src/apyfixed.h
src/apyfloat.cc
src/apytypes_common.h
src/apytypes_wrapper.cc

Fix normalized, add quantization mode

---

lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc

Increase test coverage and remove unreachable code. Also improve the test cases for long formats. Related to #236.

Increase test coverage of floating-point division

---

lib/test/apyfloatarray/test_arithmetic.py

Primarily relevant for coverage during refactoring.

Add more tests for float array multiplication

---

.github/workflows/run_coverage.yml
docs/Makefile
docs/api/apyfloatarray.rst
docs/api/context.rst
lib/test/apyfixed/test_representation.py
lib/test/apyfloat/test_representation.py
src/apyfixed.cc
src/apyfloat.cc
src/apyfloat.h
src/python_util.h

And replace references to pybind11 with nanobind

Improve LaTeX output

---

lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc

Increase test coverage of miscellaneous things in APyFloat, including power function and addition. Related to #236.

Increase test coverage for APyFloat

---

lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc
src/apyfloat_util.cc
src/apyfloat_util.h

Faster integer power for floating-point

---

.github/workflows/documentation.yml
docs/_plots/performancescale.py
docs/api/apyfixedarray.rst
docs/api/apyfloat.rst
docs/api/apyfloatarray.rst
docs/api/quantizationoverflow.rst
lib/test/apyfixedarray/test_arithmetic.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_util.cc
src/apyfloat_util.h
src/apyfloatarray.cc
src/apyfloatarray.h

And documentation improvements and fast path for fixed-point array addition/subtraction with identical word lengths.

MInor refactoring and inlining + fast path

---

src/apyfixedarray.cc
src/apyfloatarray.cc

Seems unlikely that negation should be slower than addition...

Use size instead of fold_shape where possible

---

src/apyfloatarray.cc

Less allocation and more efficient copying

Faster mat mul

---

lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc

Use `cast_mantissa` for multiplication and the power function to improve performance.

Improve floating-point performance

---

src/apyfloat.cc
src/apyfloat.h
src/apyfloatarray.cc

Special mantissa cast for subnormals.
Remove variable, refactor special case-handling.

Some refactoring

---

docs/api/apyfloat.rst
lib/test/apyfloat/test_comparisons.py
lib/test/apyfloat/test_methods.py
lib/test/apyfloatarray/test_methods.py
src/apyfixed.cc
src/apyfixed.h
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc
src/apyfloatarray.cc

~Wasn't able to add overloads for double comparisons though...~
Closes #287

Proper comparison of APyFloat vs APyFixed vs double

---

lib/test/apyfixed/test_methods.py
lib/test/apyfixedarray/test_methods.py
lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloat/test_methods.py
lib/test/apyfloatarray/test_arithmetic.py
lib/test/apyfloatarray/test_methods.py
src/apyfloat.cc
src/apyfloatarray.cc

And some comments/refactoring.
I didn't find any round-trip conversion tests, but maybe there exists some?

More tests

---

lib/test/apyfloat/test_comparisons.py
src/apyfloat.cc

Fix comparison between +/- zero

---

lib/test/apyfixed/test_quantization.py
src/apyfixed.cc
src/apytypes_util.h

src: fix fixed-point quantization memory access bug, closes #335

---

src/apytypes_util.h

src: remove vectors in limb_vector_add/sub_pow2()

---

.gitignore
lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloatarray/test_arithmetic.py
src/apyfloat.cc
src/apyfloatarray.cc

Fix multiplication between normal and subnormal numbers

---

docs/api/quantizationoverflow.rst
lib/test/apyfloat/test_rounding.py
src/apyfloat_util.h

Implement quantization mode `TO_AWAY` for floating-point.

Implement quantization mode TO_AWAY for floating-point

---

lib/test/apyfloat/test_rounding.py
src/apyfloat.cc
src/apyfloat_util.h

Implement quantization mode `TIES_ODD`, `TIES_POS`, and `TIES_NEG` for floating-point.
Related to #90.

Implement TIES_ODD, TIES_POS, and TIES_NEG for floating-point

---

lib/test/apyfloatarray/test_arithmetic.py
src/apyfloat.cc
src/apyfloatarray.cc

Introduce the correction from #349. 
Still subnormal does not seems correct, see #353.

Correct scalar-array mult

---

src/apyfloatarray.cc

Should be faster to use `APyFloatData` directly instead of setting and getting it.

Improve vector sum slightly

---

src/apyfloatarray.cc

Only cast once in float accumulator context

---

src/apyfloat.cc
src/apyfloat_util.h
src/apyfloatarray.cc

A step on the way to use function pointers for mantissa quantization.

Do exponent update from carry in mantissa quantization

---

src/apyfloatarray.cc
src/apyfloatarray.h

Factor out hadamard_multiplication in APyFloatArray

---

docs/api/apyfixedarray.rst
docs/api/apyfloatarray.rst
lib/test/apyfixedarray/test_constructors.py
lib/test/apyfloatarray/test_constructors.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Add from_array method to support arbitrary array libraries

---

lib/apytypes/_apytypes.pyi
lib/test/apyfixedarray/test_constructors.py
lib/test/apyfloatarray/test_constructors.py
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

src: read ndarrays in C-contiguous order

---

.github/workflows/run_coverage.yml
lib/test/apyfloat/test_arithmetic.py
src/apyfloat.cc
src/apyfloat_util.h
src/apyfloatarray.cc

Fixes fourth point in #406 
Still need to check for quantization modes to get correct results.

Fix multiplication underflow issue

---

lib/test/apyfloat/test_methods.py
lib/test/apyfloatarray/test_constructors.py
lib/test/apyfloatarray/test_methods.py
lib/test/test_contextmanagers.py
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_util.cc
src/apyfloat_util.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apytypes_common.cc
src/apytypes_common.h
src/apytypes_context_wrapper.cc

Change from std::uint8_t to int for Python interface

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/publish-test-pypi.yml
CHANGELOG.md

Only run CI buildwheel on PRs when explicitly asked for it

---

docs/cpp_api/apybuffer.rst
docs/cpp_api/apyfixed_util.rst
docs/cpp_api/apyfloat_util.rst
docs/cpp_api/apytypes_scratch_vector.rst
docs/cpp_api/index.rst
docs/development.rst
docs/index.rst
docs/publications.rst
src/apyfixed_util.h
src/apyfloat_util.h

Improve documentation

---

docs/conf.py
src/apyfixed.h
src/apyfixedarray.h
src/apyfloatarray.h
src/apytypes_common.h

Documentation fixes

---

docs/api/quantizationoverflow.rst
lib/apytypes/__init__.py

More documentation for APyFloat*

---

lib/test/apyfixedarray/test_methods.py
lib/test/apyfloatarray/test_methods.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

add squeeze

---

.github/workflows/stub-and-doctests.yml
CHANGELOG.md
docs/api/apyfixedarray.rst
docs/api/apyfloatarray.rst
docs/api/arrayfunctions.rst
docs/api/index.rst
lib/apytypes/__init__.py
lib/apytypes/__init__.pyi
lib/apytypes/_apytypes.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_array_functions.pyi
lib/apytypes/_typing.py
lib/test/test_array_functions.py
meson.build

Add squeeze utility function

---

.github/workflows/publish-test-pypi.yml

Bump CIBW to 2.19

---

.github/workflows/publish-test-pypi.yml
CHANGELOG.md

This PR adds a source distribution build-step (including uploading) to the apytypes publishing workflow.
Closes #452 

ci: build and publish source distribution

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
lib/test/apyfixedarray/test_methods.py
lib/test/apyfloatarray/test_methods.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc
src/apytypes_util.h

Added Sum, NanSum, CumSum and NanCumSum to both APyFixedArray and APyFloatArray. Related to #303.

Added Sum,NanSum, CumSum and NanCumSum

---

.github/workflows/documentation.yml
.pre-commit-config.yaml

Fix doc build and update pre-commit hooks

---

docs/conf.py
docs/development.rst

doc: fix development reference, closes #461

---

CHANGELOG.md
lib/test/apyfixed/test_constructors.py
lib/test/apyfixedarray/test_constructors.py
src/apyfixed_util.cc
src/apyfixedarray.cc
src/array_utils.h

src: fix get_data_from_double() shift UB, closes #487

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
lib/test/apyfixedarray/test_methods.py
lib/test/apyfloatarray/test_methods.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Max, Min, NanMax and NanMin

---

.github/workflows/publish-test-pypi.yml
.github/workflows/tests.yml
src/python_util.h

ci: revert to windows-latest runner

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_array_functions.pyi
lib/test/test_array_functions.py
src/apyfixedarray_wrapper.cc
src/apyfloat_util.h
stubgen.sh

lib: correct array creation functions

---

lib/test/apyfixedarray/test_methods.py
src/apyfixedarray.cc
src/apyfixedarray.h

src: APyFixedArray.to_bits(): return shortest dtype

---

CHANGELOG.md
docs/api/apyfloatarray.rst
lib/test/apyfloatarray/test_methods.py
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat_util.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Adding `to_bits` to `APyFloatArray`.

Add APyFloatArray.to_bits()

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
lib/test/apyfixedarray/test_get_item.py
lib/test/apyfixedarray/test_methods.py
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_iterator.cc
src/apytypes_util.h

src: `APyFixedArray.__getitem__`: `int`, `slice`, `ellipsis`, and `tuple` thereof support

---

.github/workflows/publish-test-pypi.yml

ci: fix publish workflow [2]

---

.clang-format
.markdownlint.json
.pre-commit-config.yaml
CHANGELOG.md
src/apyfloatarray.cc

src: fix APyFloatArray.cumsum memory bug, closes #505

---

CHANGELOG.md
lib/test/apyfixedarray/test_arithmetic.py
lib/test/apyfixedarray/test_matmul.py
src/apyfixed_util.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apytypes_util.h

src: APyFixedArray, various fixes to multi-limb multiplication methods

---

src/apyfixed.cc

src: APyFixed, patch assertion error

---

CHANGELOG.md
lib/test/apyfixed/test_methods.py
src/apyfixed.cc

src: subnormal support in `APyFixed.__float__()` and `APyFixed.from_float()`

---

lib/test/apyfixed/test_arithmetic.py
src/apyfixed.cc

src: fix private method APyFixed._is_positive

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
lib/test/apyfloatarray/test_methods.py
src/apyfloat.cc
src/apyfloat.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc

Closes #526.
(The code coverage seems to go down by 0.04%, but all new code is indeed tested and other test cases has not been altered. The decline in code coverage can therefore be dismissed.)

Add `APyFloatArray.from_bits`

---

src/apyarray.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloatarray.cc
src/apyfloatarray.h

src: move `broadcast_to` to APyArray

---

lib/test/apyfixedarray/test_methods.py
lib/test/apyfloatarray/test_methods.py
src/apyarray.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/array_utils.h
stubgen.sh

src: move `reshape` to `APyArray`

---

lib/test/apyfixedarray/test_methods.py
src/apyarray.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/array_utils.h

src: move `transpose`, `squeeze`, `flatten`, and `ravel` to APyArray

---

CHANGELOG.md
subprojects/nanobind.wrap
subprojects/robin-map.wrap

Fix the issue with nanobind cocotb interaction. Closes #533 

Fix nanobind interaction with cocotb

---

src/apyarray.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloatarray.cc
src/apyfloatarray.h

Move `swapaxes` to `APyArray`.

src: move `swapaxes` to APyArray

---

CHANGELOG.md

update changelog for v0.2.2

---

.github/workflows/tests.yml

Test with free-threaded Python

---

lib/test/apyfixedarray/test_get_item.py
lib/test/apyfloatarray/test_get_item.py
src/apyarray.h

Use recursive descent in `APyArray::get_item_tuple`. This is a preparation for `__setitem__`.

src: use recursive descent in `APyArray::get_item_tuple`

---

src/apyarray.h

src: `APyArray.__setitem__` cleanup

---

.github/dependabot.yml

Add dependabot script for updating GitHub Actions

---

.github/workflows/documentation.yml
.github/workflows/run_coverage.yml
.github/workflows/tests-debug-memcheck.yml
.github/workflows/tests-min-deps.yml
docs/conf.py
examples/fp8_multiplier.vhdl
examples/test_fp8_mul.py
lib/test/cocotb/test_cocotb_examples.py
pyproject.toml

In this PR:
* Add running the cocotb example as part of the documentation. The test output is unfortunately not captured, see comment below.
* Minimize the dependency to cocotb.
* Replace the VHDL implementation with a solution using `float_pkg` from VHDL-2008.

Run the cocotb example in docs, and cleanup dependencies

---

CHANGELOG.md
subprojects/nanobind.wrap

bump nanobind to v2.2.0

---

CHANGELOG.md
docs/api/index.rst
docs/api/utils.rst
lib/apytypes/__init__.py
lib/apytypes/__init__.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_utils.py
lib/apytypes/_utils.pyi
lib/test/test_utils.py
meson.build
stubgen.sh

Add utility functions

---

CHANGELOG.md
docs/api/utils.rst
lib/apytypes/__init__.py
lib/apytypes/__init__.pyi
lib/apytypes/_array_functions.pyi
lib/apytypes/_utils.py
lib/apytypes/_utils.pyi
lib/test/test_utils.py

Add fn utility function

---

lib/test/apyfixed/test_arithmetic.py
lib/test/apyfloat/test_arithmetic.py
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_util.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfixedarray_wrapper.cc
src/apyfloat_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc
src/apytypes_util.h

Some fixed-point casting (quantization and overflowing) cleanups that will help implement `APyCFixed`.

src: fixed-point casting cleanup

---

src/apyfixed_wrapper.cc
src/apyfixedarray_wrapper.cc
src/apyfloat_wrapper.cc
src/apyfloatarray_wrapper.cc

Fix for building APyTypes on RHEL 8.

src: fix compilation for RHEL8

---

.github/workflows/publish-test-pypi.yml
.github/workflows/tests.yml

ci: bump macos-12 runner to macos-13

---

CHANGELOG.md
docs/api/apycfixed.rst
docs/api/index.rst
lib/apytypes/__init__.py
lib/apytypes/__init__.pyi
lib/apytypes/_apytypes.pyi
lib/apytypes/_utils.pyi
lib/test/apycfixed/test_arithmetic.py
lib/test/apycfixed/test_constructors.py
lib/test/apycfixed/test_methods.py
lib/test/apycfixed/test_representation.py
lib/test/apyfixed/test_arithmetic.py
lib/test/apyfixed/test_methods.py
lib/test/apyfixed/test_not_implemented.py
lib/test/apyfixed/test_overflow.py
lib/test/apyfixed/test_quantization.py
lib/test/apyfixed/test_representation.py
meson.build
src/apycfixed.cc
src/apycfixed.h
src/apycfixed_wrapper.cc
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_util.h
src/apyfixed_wrapper.cc
src/apyfixedarray.cc
src/apytypes_fwd.h
src/apytypes_wrapper.cc

This PR adds the complex-valued fixed-point scalar data type `APyCFixed`.

src: add type APyCFixed

---

CHANGELOG.md
src/apyarray.h
src/apycfixed.h
src/apyfixed.cc
src/apyfixed.h
src/apyfixed_util.cc
src/apyfixed_util.h
src/apyfixedarray.cc
src/apyfixedarray.h
src/apyfloat.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/array_utils.h

Various fixes and cleanup
Closes #504 

src: minor fixes after adding `APyCFixed`

---

.github/workflows/documentation.yml
lib/apytypes/__init__.pyi
lib/apytypes/_apytypes.pyi
lib/apytypes/_utils.py
lib/apytypes/_utils.pyi
lib/test/test_utils.py
src/apyarray.h
src/apyfixedarray.cc
src/apyfixedarray_wrapper.cc
src/apyfloatarray.cc
src/apyfloatarray_wrapper.cc

Support complex scalars in fx

---

src/apyfixedarray.h
src/apyfloatarray.h

src: make `APyFloatArray` constructors public

---

.github/workflows/codeql.yml
.github/workflows/documentation.yml
.github/workflows/publish-test-pypi.yml
.github/workflows/run_coverage.yml
.github/workflows/stub-and-doctests.yml
.github/workflows/tests-cocotb.yml
.github/workflows/tests-debug-memcheck.yml
.github/workflows/tests-min-deps.yml
.github/workflows/tests.yml

zizmor https://woodruffw.github.io/zizmor/ is a linter for GitHub actions. I've fixed most of the things it complained about, mainly safety related.

Use the zizmor Github Actions linter

---

CHANGELOG.md
pyproject.toml
subprojects/fmt.wrap
subprojects/highway.wrap
subprojects/nanobind.wrap

Update nanobind to 2.4

---

.github/workflows/codeql.yml
.github/workflows/publish-test-pypi.yml
.github/workflows/stub-and-doctests.yml

[MNT] Use explicit versions of actions

---

.github/workflows/tests-debug-memcheck.yml
src/apyfixed_util.h

Use mpn_add_n instead of mpn_add where possible

---

lib/test/apyfixed/test_arithmetic.py
lib/test/apyfixedarray/test_methods.py

Add more tests for special cases

---

src/apycfixedarray.cc
src/apyfixed.cc
src/apyfixed_util.h
src/apyfixedarray.cc
src/apytypes_mp.cc
src/apytypes_mp.h
src/apytypes_util.h
src/python_util.h

Clean-up of MP code

---

lib/test/apyfixed/test_constructors.py
src/python_util.h

Add test for conversion and to see if special cases are used

---

.github/workflows/publish-test-pypi.yml
CHANGELOG.md
src/apytypes_util.h

Fix i686 build

---

lib/apytypes/_apytypes.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_utils.py
lib/apytypes/vhdl.py
src/apycfixed_wrapper.cc
src/apycfixedarray_wrapper.cc
src/apycfloat_wrapper.cc
src/apyfixed_wrapper.cc
src/apyfixedarray_wrapper.cc
src/apyfloat_wrapper.cc
src/apyfloatarray_wrapper.cc
src/apytypes_wrapper.cc

Improve types in docs

---

lib/apytypes/_apytypes.pyi
src/apyfixed_wrapper.cc

Fix cast example for APyFixed

---

CHANGELOG.md
docs/comparison.rst
docs/licenses.rst
src/apytypes_mp.cc

Inline stuff in mult and div plus some doc wording

---

src/apytypes_mp.cc

More cleanup of MP code

---

CHANGELOG.md
src/apycfixedarray.cc
src/apyfixedarray.cc
src/apytypes_simd.cc
src/apytypes_simd.h

Use SIMD for fixed-point array abs and negation

---

src/apytypes_mp.h
src/apytypes_util.h

Simplify multi-limb negate

---

src/apycfixed.cc
src/apyfixed.cc
src/apyfixed_util.h
src/apytypes_mp.cc
src/apytypes_mp.h

Use long multiplication and specialized square

---

benchmark/ci_fixed_array_benchmarks.py

Add more fixed-point array benchmarks

---

.github/workflows/documentation.yml
benchmark/ci_cfixed_scalar_benchmarks.py

Add APyCFixed benchmarks

---

lib/test/apyfixedarray/test_arithmetic.py
src/apyfixed.cc
src/apyfixedarray.cc
src/apytypes_mp.cc
src/apytypes_util.h

More use of long multiplication

---

benchmark/ci_fixed_array_benchmarks.py
lib/test/apyfixedarray/test_matmul.py

Add test and benchmark for two limb matmul results

---

lib/test/apyfixedarray/test_matmul.py
src/apyfixedarray.cc
src/apytypes_util.h

MSVC support for two-limb matrix multiplication

---

.github/workflows/tests-32-bits.yml
meson.build
meson.options

Add 32-bit test

---

benchmark/ci_fixed_array_benchmarks.py
benchmark/ci_float_array_benchmarks.py
docs/api/apycfixedarray.rst
docs/conf.py
docs/performance.rst
examples/test_fp8_mul.py
lib/apytypes/_apytypes.pyi
src/apyfloatarray_wrapper.cc
src/apytypes_simd.cc

Documentation for limbs and benchmarks for convolve

---

benchmark/ci_fixed_array_benchmarks.py
benchmark/ci_float_array_benchmarks.py

Fix benchmarks so all use signed arguments

---

src/apyfixed_util.h
src/apyfixedarray.cc

Specialize method when there is no shift

---

src/apycfixed.cc
src/apyfixedarray.cc
src/apytypes_mp.cc
src/apytypes_mp.h

Two-limb special case for complex multiplication

---

lib/test/apycfixedarray/test_arithmetic.py

Add tests for varying word length for complex fixed arrays

---

.github/workflows/tests-32-bits.yml
lib/test/apycfixedarray/test_arithmetic.py
src/apycfixed.cc
src/apycfixed_util.h
src/apycfixedarray.cc

Special case for two-limb complex multiplication

---

.github/workflows/documentation.yml
.github/workflows/tests-cocotb.yml
.github/workflows/tests.yml
docs/cpp_api/apycfixed.rst
docs/cpp_api/apycfixed_util.rst
docs/cpp_api/apycfixedarray.rst
lib/test/apycfixed/test_arithmetic.py
lib/test/apyfixed/test_arithmetic.py
src/apycfixed.cc
src/apycfixed_util.h
src/apycfixedarray.cc

Complex multiplication refactor and complex type docs

---

docs/cpp_api/index.rst
src/apycfixedarray.cc
src/apyfixed_util.h
src/apyfixedarray.cc
src/apytypes_util.h

Rewrite vector negation

---

src/apycfixedarray.cc
src/apyfixedarray.cc
src/apytypes_simd.cc
src/apytypes_simd.h

Add SIMD Not

---

lib/test/apyfloat/test_methods.py
lib/test/apyfloat/test_rounding.py
lib/test/apyfloatarray/test_arithmetic.py
pyproject.toml

Do not compare with True/False in tests

---

src/apycfixed.cc
src/apycfixedarray.cc
src/apyfixed.cc
src/apyfixed_util.h
src/apyfixedarray.cc

Only pass frac_bits to fixed_point_to_double

---

CHANGELOG.md
docs/licenses.rst
examples/apyfixed.py
examples/apyfloat.py
examples/numpy_integration.py
examples/test_fp8_mul.py

Doc-changes for v 0.3.0

---

.pre-commit-config.yaml
docs/conf.py
lib/apytypes/_apytypes.pyi
src/apyarray.h
src/apycfixed.cc
src/apycfixedarray.cc
src/apyfixed_util.h
src/apyfixedarray.cc
src/apyfloatarray.cc
src/apyfloatarray_wrapper.cc
src/apytypes_scratch_vector.h
src/apytypes_util.h

Unify and fix docs a bit, update pre-commit hooks, and change link color

---

docs/api/apycfixedarray.rst
docs/api/apyfixedarray.rst
docs/api/apyfloat.rst
docs/api/apyfloatarray.rst
docs/conf.py
lib/apytypes/_apytypes.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_utils.py
src/apycfixed_wrapper.cc
src/apycfixedarray_wrapper.cc
src/apyfixedarray_wrapper.cc

More documentation fixes

---

.github/workflows/stub-and-doctests.yml
README.md
lib/apytypes/_apytypes.pyi
lib/apytypes/_array_functions.py
lib/apytypes/_utils.py
src/apycfixed_wrapper.cc
src/apycfixedarray_wrapper.cc
src/apyfixed_wrapper.cc
src/apyfixedarray_wrapper.cc
src/apyfloat_wrapper.cc
src/apyfloatarray_wrapper.cc

Even more doc fixes

---

CHANGELOG.md
lib/apytypes/_array_functions.py
lib/test/test_array_functions.py

Support APyCFixedArray in ones_like and zeros_like

---

src/apyfloat.h
src/apyfloatarray.h
src/apytypes_common.h
src/apytypes_fwd.h

Add comments to some functions and variables that are missing it in `APyFloat(Array)`. This will remove some warnings in doxygen.

Add comments to functions and variables in C++ for `APyFloat(Array)`

---

benchmark/ci_fixed_array_benchmarks.py
benchmark/ci_float_array_benchmarks.py

Add array-scalar division benchmarks

---

lib/test/apyfixedarray/test_arithmetic.py
src/apyfixedarray.cc
src/apytypes_mp.cc
src/apytypes_mp.h

Improved division for constant denominator + documentation fixes

---

CHANGELOG.md
lib/test/apyfloat/test_methods.py
src/apyfixed.cc
src/apyfixed.h
src/apyfloat.cc

Fix conversion from APyFixed to APyFloat

---

CHANGELOG.md
lib/test/apyfixedarray/test_arithmetic.py
src/apycfixedarray.cc

This failed in #670 so adding here first.
EDIT: Closes #673 

Add test case for division

---

CHANGELOG.md
lib/test/apyfloat/test_arithmetic.py
src/apyfloat_util.h

src: fix `APyFloat` addition of zeros of different specs

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
src/apyfloat_wrapper.cc

Chores for v0.3.1

---

.github/workflows/tests.yml

Available in Python-action 5.5.

Use GitHub version of Python 3.13t

---

src/apyfixed_util.h
src/apytypes_mp.h

src: Apple Clang lint fixes

---

benchmark/ci_cfixed_scalar_benchmarks.py
benchmark/ci_fixed_array_benchmarks.py
benchmark/ci_fixed_scalar_benchmarks.py
benchmark/ci_float_array_benchmarks.py
benchmark/ci_float_scalar_benchmarks.py
docs/_plots/quantization.py
docs/conf.py
examples/test_fp8_mul.py
examples/vectorrotation.py
lib/apytypes/_array_functions.py
lib/apytypes/_utils.py
lib/apytypes/vhdl.py
lib/test/conftest.py
pyproject.toml

More lints

---

.clangd-gen.py
CHANGELOG.md
examples/test_fp8_mul.py
lib/apytypes/vhdl.py
lib/test/test_codegen.py
pyproject.toml
subprojects/fmt.wrap

Enforce use of pathlib

---

meson.build
src/apytypes_mp.cc

The fmt-documentation was incorrect.

Make fmt actually header-only

---

lib/apytypes/_apytypes.pyi
src/apyfloatarray_wrapper.cc

docs: cleanup APyFloatArray examples

---

meson.build
src/apycfixed.h
src/apycfixedarray.h
src/apyfixed.h
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat.h
src/apyfloatarray.h

Bring up the warning level during building and fix some warnings.
To be merged after:
* #710

build: add option `warning_level=2` and add fixes

---

src/apyfixed.h
src/apyfixed_util.h
src/apyfixedarray.cc
src/apyfloat.cc
src/apyfloat_util.h
src/apyfloatarray.cc
src/apytypes_util.h

Add std:: in front of remaining (u)intXX_t

---

.codecov.yml
src/apytypes_intrinsics.h
src/apytypes_mp.cc

Use intrinsics in division functions

---

src/apyfloat_util.h

Rewrite a bit of code

---

src/apyfloat_util.h

Fix introduced issue and rewrite

---

.github/workflows/stub-and-doctests.yml
CHANGELOG.md
docs/api/apyfloat.rst
lib/apytypes/_apytypes.pyi
lib/test/apyfloat/test_methods.py
src/apyfloat.cc
src/apyfloat.h
src/apyfloat_wrapper.cc

Closes #718 
Also update nanobind in CI to match the TOML file.

Add `APyFloat.zero` and update nanobind in CI

---

lib/test/apyfixed/test_constructors.py
lib/test/apyfixed/test_methods.py
lib/test/apyfixed/test_quantization.py
lib/test/apyfloat/test_arithmetic.py
lib/test/apyfloatarray/test_arithmetic.py
lib/test/apyfloatarray/test_matmul.py
lib/test/test_array_functions.py
lib/test/test_broadcasting.py
src/apyarray.h
src/apycfixed.h
src/apycfixed_wrapper.cc
src/apycfixedarray.h
src/apycfloat.cc
src/apycfloat_util.h
src/apyfixed.h
src/apyfixed_util.h
src/apyfixedarray.h
src/apyfloat.cc
src/apyfloat_util.h
src/apyfloatarray.cc
src/apyfloatarray.h
src/apyfloatarray_wrapper.cc
src/apytypes_common.h
src/apytypes_util.h
src/array_utils.h
src/broadcast.h
src/ieee754.h

Fixes various typos / grammatical issues in the code for clarity.

Typographical Fixes

---

CHANGELOG.md
lib/apytypes/_apytypes.pyi
subprojects/nanobind.wrap
subprojects/robin-map.wrap

Update nanobind to 2.8

---

.github/dependabot.yml
.github/workflows/run_coverage.yml
.github/workflows/stub-and-doctests.yml
.github/workflows/tests-32-bits.yml
.github/workflows/tests-cocotb.yml
.github/workflows/tests-debug-memcheck.yml
.github/workflows/tests-min-deps.yml
.github/workflows/tests.yml
.pre-commit-config.yaml

Set default permissions for actions

---

docs/publications.rst
examples/numpy_integration.py
examples/reciprocal_lookup.py

This PR adds two conference papers, both accepted to Asilomar 2025, to the list of publications using/citing APyTypes.
Small corrections in the documentation are also included.

Add two papers citing APyTypes to the documentation

---

examples/test_fp8_mul.py
pyproject.toml
src/apyfloat_util.h

Sub-optimizations plus cocotb 2

---

.github/workflows/codeql.yml
.github/workflows/documentation.yml
.github/workflows/publish-test-pypi.yml
.github/workflows/run_coverage.yml
.github/workflows/stub-and-doctests.yml
.github/workflows/tests-32-bits.yml
.github/workflows/tests-cocotb.yml
.github/workflows/tests-debug-memcheck.yml
.github/workflows/tests-min-deps.yml
.github/workflows/tests.yml

Closes #764 
Seems to work:
```
Build targets in project: 33
apytypes 0.4.0.dev86+g5ae23405e
Subprojects
fmt         : YES
highway     : YES
nanobind    : YES
robin-map   : YES (from nanobind)
```

Always fetch tags during checkout

---

CHANGELOG.md
examples/reciprocal_lookup.py
lib/apytypes/_array_functions.py

Closes #771
(Also, parts of #730 )

Make arguments keyword only for array utility functions
