apytypes_stubgen.sh, lib/apytypes/__init__.pyi, lib/apytypes/_apytypes.pyi, meson.build
This PR adds Python stubs (`.pyi`) for apytypes and also suggests a way for automatic stub generation. The stub generation depends on [pybind11-stubgen](https://pypi.org/project/pybind11-stubgen/0.10.2/). pybind11-stubgen takes the written docstrings from the C++ wrapper source files and adds them to the stub-files which makes using apytypes significantly easier as it includes the documentation in the Python stubs. Further, this should keep the stub documentation consistent with the actual documentation produced by Doxygen.
See `apytypes_stubgen.sh` for example usage of pybind11-stubgen with apytypes.
pybing11-stubgen requires that apytypes be installed before generating the stubs. This essentially makes installing fresh stubs a three-step process:
* First, the entire project has to be …
=> Python stub generation for apytypes (#11)

.github/workflows/run_coverage.yml
I don't yet know if this is desirable. The general rule of thumb for code-coverage builds is to set the optimization level as low as possible, as lines from the initial source code will have a better correlation to the reported source code coverage.
I noticed the following difference in the reported code coverage when lowering the optimization level for the code-coverage build:
* There is a greater number of total lines reported (as missing, partial, or hit) in the codebase
* There is a greater number of lines reported as having hits
* The overall code-coverage percentage is lowered as there are many more new lines reported in  the coverage report
EDIT:
Subjectively, I also think that the reported partial hits make more sense when studying the coverage report from the non-optimized build.
=> coverage: lower optimization level on code-coverage builds

lib/test/test_floating_point.py, src/apyfloat.h, src/apyfloat_wrapper.cc
This PR, relating to #16, adds comparisons between APyFloat with int, floats, and APyFloat.
The comparison is made by the object converting itself to a Python float. An obvious edge case here is if one would simulate a number format that doesn't fit inside the double precision format, but since high-precision simulations isn't really the use case this should be acceptable. This also allows for comparisons between APyFloat and APyFixed, by converting both to Python floats. Note that comparisons between two APyFloats objects is still done the same way as before and are not silently converted to floats.
Removed the properties `is_sign_neg` and `is_zero`, but added `bias` since it was missing from before.
=> APyFloat: add comparisons with APyFixed/float/int #16

.gitignore, lib/apytypes/__init__.py, lib/apytypes/_version.py.in, meson.build, pyproject.toml, src/apytypes_wrapper.cc
Now it is enough to change the version in `meson.build` (and `apytypes.__version__` works).
This will create a file `_version.py` in the build directory.
=> Simplify version management

.github/workflows/run_coverage.yml, lib/apytypes/_apytypes.pyi, lib/test/apyfixedarray/test_methods.py, pyproject.toml, src/apyfixed.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc
Using method `APyFixed.to_numpy()` requires NumPy to be installed. Not having NumPy installed when using `to_numpy()` triggers a `MoudleNotFoundError` exception.
Example:
```Python
=================================== FAILURES ===================================
________________________________ test_to_numpy _________________________________
def test_to_numpy():
float_seq = [
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
[[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]],
]
fx_arr = APyFixedArray.from_float(float_seq, bits=10, int_bits=10)
>       np_arr = fx_arr.to_numpy()
E       ModuleNotFoundError: No module named 'numpy'
lib/test/apyfixedarray/test_methods.py:24: ModuleNotFoundError
=========================== short test summary info ============================
FAILED …
```
=> src: add APyFixedArray.to_numpy()

lib/apytypes/__init__.py, lib/test/apyfloat/test_rounding.py, lib/test/test_contextmanagers.py, src/apyfloat.cc, src/apytypes_common.cc, src/apytypes_common.h, src/apytypes_context_wrapper.cc, src/apytypes_wrapper.cc
Adding support for the new rounding methods `TIES_ZERO`, `JAM`, `STOCHASTIC_WEIGHTED`, and `STOCHASTIC_EQUAL` in APyFloat:
* Ties-to-zero: Round to closest number but ties are rounded towards zero.
* Jamming: Truncate and force LSB to 1, also known as Von-Neumann rounding.
* Stochastic-weighted: rounds up with a probability proportional to the relative distance $(x-\lfloor x \rfloor)/(\lceil x \rceil - \lfloor x \rfloor)$.
* Stochastic-equal: rounds up and down with equal probability.
**(Note, stochasting-weighted doesn't truly work for addition and subtraction due  to the sticky bit that is used.)**
Two new functions are also added to the Python API: `set_rounding_seed` and `get_rounding_seed`.
Additionally, an optional argument is added to `RoundingContext` such that a seed can be …
=> More rounding modes for APyFloat

lib/test/apyfloatarray/test_constructors.py, lib/test/apyfloatarray/test_matmul.py, lib/test/apyfloatarray/test_methods.py, lib/test/apyfloatarray/test_representation.py, lib/test/test_contextmanagers.py, src/apyfloatarray.cc, src/apyfloatarray.h, src/apytypes_common.cc, src/apytypes_common.h, src/apytypes_context_wrapper.cc
This PR adds support for `AccumulatorContext` for `APyFloatArray`.
The same class is used for both APyFixedArray and APyFloatArray. Keyword only arguments are now enforced to handle this, and a `ValueError` exception is thrown if one tries to mix the parameters.
Note, the way `AccumulatorContext` interracts with `QuantizationContext` is by `AccumulatorContext` only changes the quantization mode for matmul. However I'm not if this is the desired behavior, or if `AccumulatorContext` should only change the mode for other operations. What do you guys think? My impression is that `AccumulatorContext` should change the characteristics of the accumulator.
Example:
```Python
with QuantizationContext(QuantizationMode.TO_POS):
with AccumulatorContext(exp_bits=5, man_bits=3, …
```
=> AccumulatorContext support for APyFloatArray

src/apybuffer.h, src/apytypes_common.h, src/apytypes_util.h, src/ieee754.h, src/python_util.h
It is now possible to mark functions as conditional  `inline` with the `APY_INLINE` macro:
```C++
[[maybe_unused]] static APY_INLINE std::size_t bits_to_limbs(std::size_t bits)
```
Functions marked with conditional inlining will not be inlined when the `-D_APY_PROFILING` macro is set. This can be done with:
```bash
python3 -m pip install --config-settings=setup-args="-Dcpp_args=-D_APY_PROFILING" . -v
```
EDIT:
Closes #136
=> src: add command-line support for conditional code inlining

lib/test/apyfixed/test_quantization.py, src/apyfixed.cc
Fix a memory bug where a huge narrowing (multiple limb narrowing) during a `APyFixed::_cast` can access data out of bounds.
=> src: fix memory access bug in APyFixed::_cast()

lib/test/apyfixedarray/test_matmul.py, src/apybuffer.h, src/apyfixed.cc, src/apyfixed.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc
```python
from apytypes import APyFixedArray
a = APyFixedArray([range(100), range(100), range(100)], bits=32, int_bits=16)
b = a.T
for _ in range(10000):
c = b @ a
```
```
❯ time python3 bench_matmul.py
python3 bench_matmul.py  22,76s user 0,00s system 99% cpu 22,766 total
```
```
❯ time python3 bench_matmul.py
python3 bench_matmul.py  2,78s user 0,00s system 99% cpu 2,787 total
```
=> src: optimizations to APyFixedArray::matmul()

lib/test/apyfixed/test_arithmetic.py, src/apyfixed.cc
```python
from apytypes import APyFixed
from time import time
a = APyFixed(123456, bits=24, int_bits=12)
b = APyFixed(654321, bits=25, int_bits=12)
t1 = time()
for i in range(1000000):
c = a + b
t2 = time()
print(f"Add: {(t2 - t1)*1e3} ms")
t1 = time()
for i in range(1000000):
c = a - b
t2 = time()
print(f"Sub: {(t2 - t1)*1e3} ms")
t1 = time()
for i in range(1000000):
c = a * b
t2 = time()
print(f"Mul: {(t2 - t1)*1e3} ms")
```
```
Add: 209.1515064239502 ms
Sub: 210.9079360961914 ms
Mul: 237.6255989074707 ms
```
```
Add: 178.8461208343506 ms
Sub: 179.54015731811523 ms
Mul: 167.3893928527832 ms
```
=> APyFixed: specialize arithmetic when result fits single limb

lib/apytypes/_apytypes.pyi, lib/test/apyfixed/test_arithmetic.py, src/apyfixed.cc, src/apyfixed.h, src/apyfixed_wrapper.cc, src/apytypes_util.h
This PR adds the following methods to `APyFixed`:
* `APyFixed.leading_zeros() -> int`
* `APyFixed.leading_ones() -> int`
* `APyFixed.leading_signs() -> int`
* `APyFixed.leading_fractional_zeros() -> int`
=> src: add APyFixed.leading_* methods

src/apyfixedarray.cc, src/apyfixedarray.h, src/apytypes_util.h
```Python
from apytypes import *
from time import time
import numpy as np
a = APyFixedArray.from_float(np.random.rand(200, 200) - 0.5, 200, 1)
b = APyFixedArray.from_float(np.random.rand(200, 200) - 0.5, 200, 1)
t1 = time()
for i in range(10000):
a + b
t2 = time()
print(f'[200 x 200] 200-bit addition: {(t2 - t1)*1e6 / 10000} us per addition')
t1 = time()
for i in range(10000):
a - b 
t2 = time()
print(f'[200 x 200] 200-bit subtraction: {(t2 - t1)*1e6 / 10000} us per subtraction')
```
```
[200 x 200] 200-bit addition: 1035.451579093933 us per addition
[200 x 200] 200-bit subtraction: 986.5080833435059 us per subtraction
```
```
[200 x 200] 200-bit addition: 148.31440448760986 us per addition
[200 x 200] 200-bit subtraction: 162.70325183868408 us per subtraction
```
=> src: equally many limb-optimize APyFixedArray::operator+/-()

docs/api/quantizationoverflow.rst, lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_rounding.py, lib/test/apyfloatarray/test_constructors.py, src/apyfloat.cc, src/apyfloat.h
Also refactors addition slightly as a step towards special casing for single limb computations.
We should discuss how to deal with jamming for some cases. I'm still a bit doubtful if we actually should jam for adding/subtracting with zero. The argument is probably more for multiplying with zero, which will need to decide which exponent the jammed bit should have. That probably leads to that we should not jam for multiplication with zero (or division of zero by a non-zero value), so I actually doubt that we should jam for adding/subtracting by zero. By the way, I think that some operations suffer from double rounding. Not sure if it ever will affect any actual result though.
=> Rewrite APyFloat operators

lib/test/apyfloat/test_arithmetic.py
Increase test coverage and remove unreachable code. Also improve the test cases for long formats. Related to #236.
=> Increase test coverage for floating-point multiplication

lib/test/apyfloat/test_methods.py
Increase test coverage for miscellaneous things, such as constructor raises and warnings for deprecated functions, in APyFloat.
=> Increase test coverage in APyFloat

lib/test/apyfloat/test_arithmetic.py, src/apyfloat.cc
Use integer operations when the intermediate result can fit within one `man_t` (64-bits). This is related to #124.
Note that the test for floating-point addition with long formats uses binary64, as these will now use the fast path this test must be re-written as well.
=> Add fast path for floating-point addition

lib/test/apyfloat/test_arithmetic.py, src/apyfloat.cc, src/apyfloat.h
Makes the `_cast` method not as big, and will hopefully improve the performance of floating-point addition.
=> Refactor mantissa quantization to its own method

lib/test/apyfloat/test_arithmetic.py, src/apyfloat.cc
Fix normalization (i.e. handling of carries) in fast path floating-point power.
Closes #253.
=> Fix normalization in fast path floating-point power

lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_methods.py, src/apyfloat.cc
Fixes #288. 
The method `_cast` did not check whether the exponent was within range when casting to a format with more mantissa bits. This was probably introduced in PR #277. 
This PR also adds an early exit when the power is 1, and also some more test cases related to casting.
=> More test cases and add overflow detection in APyFloat cast

.github/workflows/documentation.yml, .github/workflows/run_coverage.yml, .github/workflows/tests.yml, meson.build, pyproject.toml
Now it should be enough to tag a version and it will be used when building. Later dev-versions will automatically be one minor version higher.
Also enables lto, so about 300 k smaller library.
=> Update version management to use setuptools_scm

lib/test/apyfloatarray/test_matmul.py, src/apyfloatarray.cc
It should be possible to not mask away hidden one etc during computations, for even fewer operations. And get rid of bias adding and subtracting.
=> Inline addition for short word length float vector sums

src/apyfloatarray.cc, src/apyfloatarray.h
Closes #368 
(Doing it in steps instead...)
Remains:
=> Faster floating-point matrix multiplication

lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloatarray/test_arithmetic.py, src/apyfloat.cc
Setting the exponent to '1' for a certain case was missing in two places: division, and multiplication with long formats.
=> Small fix in long floating-point multiplication / division

.gitignore, docs/development.rst, lib/test/apyfloat/run_berkeley_cases.py
This PR aims to create a script such that test cases from [Berkeley TestFloat](http://www.jhauser.us/arithmetic/TestFloat-3/doc/TestFloat-general.html) can be ~~incorporated as part of an optional test suite~~ run. This should make our tests more extensive and we can be more confidant that we have bit-accurate operations. 
Berkeley TestFloat is specifically designed with the IEEE-754 standard in mind, so formats like binary16 and binary64 are supported, as well as five different quantization modes, and operations like $+, -, \times, /, \sqrt{}$ and fused-multiply add.
Using the tool [testfloat_gen](http://www.jhauser.us/arithmetic/TestFloat-3/doc/testfloat_gen.html) a range of (random) test cases can be generated, this will be used as the "backend" of the script. Besides testing …
=> Add optional test suite from Berkeley TestFloat

lib/test/apyfloat/run_berkeley_cases.py, lib/test/apyfloat/test_rounding.py, lib/test/apyfloatarray/test_arithmetic.py, src/apyfloat.cc, src/apyfloat_util.h, src/apyfloatarray.cc
Floating-point results should sometimes quantize to infinity and at other times to the maximum normal number depending on the quantization mode. Related to  #406. This will probably take a toll on the performance unfortunately.
=> Handle infinity according to quantization mode

docs/development.rst, lib/test/apyfloat/run_berkeley_cases.py
This adds the option perform tests using the array class `APyFloatArray` in the Berkeley test script. 
The added command line argument is `--array` (`-ar`).
=> Option to test arrays in Berkeley script

lib/test/apyfloat/run_berkeley_cases.py, lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_rounding.py, lib/test/apyfloatarray/test_arithmetic.py, src/apyfloat.cc, src/apyfloatarray.cc
=> Handle sign of zero correctly in floating-point addition and subtraction

lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_comparisons.py, lib/test/apyfloatarray/test_arithmetic.py, lib/test/apyfloatarray/test_constructors.py, lib/test/apyfloatarray/test_matmul.py, src/apyfloat.cc, src/apyfloat_util.cc, src/apyfloat_util.h, src/apyfloatarray.cc, src/apytypes_common.cc, src/apytypes_common.h
Support floating-point arithmetic with mixed biases, closes #322. The new bias is calculated by taking the "average".
Also added two test cases marked xfail related to the accumulator context quantizing too early, related to #422.
=> Improve support for non IEEE-like biases

lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_methods.py, lib/test/apyfloatarray/test_constructors.py, lib/test/apyfloatarray/test_matmul.py, lib/test/apyfloatarray/test_methods.py, src/apyfloat.cc, src/apyfloat_util.cc, src/apyfloat_util.h, src/apyfloat_wrapper.cc, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_wrapper.cc
=> More exception handling of formats in APyFloat

.github/workflows/publish-test-pypi.yml, README.md, lib/apytypes/__init__.pyi, pyproject.toml, src/apyfixed.cc
This workflow automizes the publishing of APyTypes:
* Publish to [test.pypi.org](test.pypi.org) on pushes to main
* Publish to [pypi.org](pypi.org) on new tags
* GitHub release on new tags
=> ci: add PyPi publishing workflow

CHANGELOG.md, lib/test/apyfloat/test_rounding.py, src/apyfloat.cc, src/apyfloat_util.h
Fixes third point in #406. Fixed that scalar floating-point multiplication was sometimes off by one LSB for directed quantization modes. Fixed jamming for subnormal numbers as well. Lastly, updated changelog.
=> Fixes in quantization for floating-point scalar multiplication

lib/test/apyfloat/test_rounding.py, src/apyfloat.cc
Fixes point five in #406, i.e. bug when casting to a subnormal number. Updated changelog.
=> Fix in 'cast' when result is subnormal

CHANGELOG.md, lib/test/apyfloat/test_methods.py, src/apyfloat.cc, src/apyfloat.h, src/apyfloat_wrapper.cc
This PR adds the methods `next_up` and `next_down` to `APyFloat`, which closes #95. Updated changelog.
=> Add methods next_up and next_down for floating-point

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, docs/api/apyfixedarray.rst, docs/api/apyfloatarray.rst, docs/cpp_api/broadcast.rst, docs/cpp_api/index.rst, lib/apytypes/_apytypes.pyi, lib/test/apyfixedarray/test_arithmetic.py, lib/test/apyfixedarray/test_matmul.py, lib/test/apyfixedarray/test_representation.py, lib/test/apyfloatarray/test_arithmetic.py, lib/test/apyfloatarray/test_representation.py, lib/test/test_broadcasting.py, src/apybuffer.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_wrapper.cc, src/apytypes_util.h, src/broadcast.h
This PR adds broadcasting support for the APyTypes array types.
Closes #302 
Also fixes a bug in `APyFixedArray.__truediv__` that would cause the program to crash on multi-limb division-by-zero.
=> src: add broadcasting support

.gitignore, CHANGELOG.md, docs/api/apyfloat.rst, lib/apytypes/__init__.py, lib/apytypes/_apytypes.pyi, src/apyfloat.h, src/apyfloat_util.h, src/apyfloat_wrapper.cc, src/apyfloatarray.h, src/apytypes_common.h
This PR contains general improvements to the documentation for the floating-point types.
Documentation regarding `APyFloatQuantizationContext`, `APyFloatAccumulatorContext`, and sign of zero will be added in a different PR.
=> Improve documentation for APyFloat*

lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloatarray/test_matmul.py, src/apyfixed.h, src/apyfloat.cc, src/apyfloat_util.cc, src/apytypes_util.h
Closes #249
@Theodor-Lindberg, before merging this, could you please help me look at the three tests that started to fail as a consequence of these two changes:
```diff
@@ -895,9 +895,7 @@ APyFloat APyFloat::operator+(const APyFloat& rhs) const
apy_res = apy_res - fx_one;
}
-    apy_res <<= res.man_bits;
-    // TODO: Get bit-pattern directly
-    res.man = (man_t)(apy_res).to_double();
+    res.man = apy_res.get_lsbs();
res.exp = new_exp;
return res;
}
```
```diff
@@ -1035,9 +1033,7 @@ APyFloat& APyFloat::operator+=(const APyFloat& rhs)
apy_res = apy_res - fx_one;
}
-    apy_res <<= man_bits;
-    // TODO: Get bit-pattern directly
-    man = (man_t)(apy_res).to_double();
+    man = apy_res.get_lsbs();
return *this;
}
```
=> src: add APyFixed.get_lsbs()

CHANGELOG.md, lib/apytypes/__init__.pyi, lib/apytypes/_apytypes.pyi, lib/test/test_contextmanagers.py, pyproject.toml, src/apyfixed_wrapper.cc, src/apyfloatarray_wrapper.cc, src/apytypes_context_wrapper.cc, stubgen.sh, subprojects/nanobind.wrap
This PR bumps the nanobind dependency from v1.9.2 to v2.0.0. It also removes all uses of keywork-only arguments that were previously used.
- Closes #446 
- Closes #11
- Closes #154
=> src: bump nanobind dependency to v2.0.0

CHANGELOG.md, lib/apytypes/_apytypes.pyi, lib/test/apyfloat/test_methods.py, src/apyfloat.cc, src/apyfloat.h, src/apyfloat_util.h, src/apyfloat_wrapper.cc
Zero was previously considered a subnormal number in APyFloat, however this is not the case in the IEEE 754 standard. This PR fixes that.
From the standard:
***"subnormal number:** In a particular format, a non-zero floating-point number with magnitude less than the magnitude of that format’s smallest normal number. A subnormal number does not use the full precision available to normal numbers of the same format."*
=> No longer consider zero a subnormal number

CHANGELOG.md, docs/api/apyfixedarray.rst, docs/api/apyfloatarray.rst, docs/api/arrayfunctions.rst, lib/apytypes/__init__.py, lib/apytypes/__init__.pyi, lib/apytypes/_apytypes.pyi, lib/apytypes/_array_functions.py, lib/apytypes/_array_functions.pyi, lib/apytypes/_typing.py, lib/test/test_array_functions.py, src/apyfixed_util.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc, src/apyfloat_util.h, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_wrapper.cc, src/array_utils.h
Added several basic array creation methods. If an integer or float is used for the full function, word lengths must be defined. For functions like ones, I removed the parameter for input data type (e.g., APyFloatArray). Instead, the user must specify exp_bits and mantissa_bits or int_bits and frac_bits to decide return type of array.
=> Array creation pr

.github/workflows/tests-debug-memcheck.yml, CHANGELOG.md, meson.build, src/apyfloat.cc, subprojects/nanobind.wrap
This PR adds a CI workflow that builds APyTypes in debug mode and runs the test-suite through Valgrind memcheck.
=> ci: add mem-check and debug-build test workflow

src/apybuffer.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_iterator.cc, src/apyfloatarray_wrapper.cc, src/apytypes_util.h
=> Move common APyArray functions to APyBuffer

CHANGELOG.md, lib/apytypes/_array_functions.py, lib/apytypes/_array_functions.pyi, lib/test/test_array_functions.py
Closes #518. If no bit-specifiers are given to `arange` the array type is deduced from `start`, `stop`, and `step`.
If the APyTypes scalars given are not of the same format, the array type will not be deduced. This behaviour is documented.
```Python
from apytypes import APyFixed, arange
arange(APyFixed(0, 4, 3), APyFixed(10, 8, 0), APyFixed(1, 2, 7))
```
=> `arange`: deduce array type based on arguments

docs/conf.py, examples/numpy.py, pyproject.toml
There is an error here @miklhh that we probably should try to sort out.
```
In [3]: filtered = signal.convolve(sig_fx, win_fx, mode='same') / sum(win_fx)
Traceback (most recent call last):
Cell In[3], line 1
filtered = signal.convolve(sig_fx, win_fx, mode='same') / sum(win_fx)
File /local/data1/miniconda3/lib/python3.10/site-packages/scipy/signal/_signaltools.py:1401 in convolve
return volume * kernel
RuntimeError: In APyFixedArray.__mul__: shape missmatch
```
A start is to write out the missmatching shapes to get some hint.
=> NumPy and SciPy example

CHANGELOG.md, lib/test/parallel/test_contexts.py, src/apyfixed_util.cc, src/apytypes_common.cc
This PR marks the global context options `thread_local`, making APyTypes ready for multi-threading.
Closes #234 
=> src: use `thread_local` storage for context settings

CHANGELOG.md, lib/test/apyfloatarray/test_matmul.py, lib/test/parallel/test_contexts.py, src/apyfloat_util.h, src/apyfloatarray.cc, src/apyfloatarray.h, src/apytypes_common.h, src/python_util.h
This method implements `FloatInnerProductFunctor`, a unified **fast** implementation of floating-point inner products that support quantization contexts and accumulator contexts and is both reusable and scalable.
=> src: add utility `FloatInnerProductFunctor`

CHANGELOG.md, lib/test/apyfixed/test_methods.py, lib/test/apyfixedarray/test_constructors.py, src/apycfixedarray.cc, src/apyfixed.cc, src/apyfixed_util.h, src/apyfixedarray.cc, src/apyfloat_util.h
Python integers are currently casted to floats as an intermediate step in `from_float` and `from_array`, thus causing issues for large integers. This PR solves that.
MRE:
```Python
import numpy as np
from apytypes import APyFixed, APyFixedArray
num =  2**64 - 1 # 18446744073709551615
APyFixedArray([num], bits=65, int_bits=65) # APyFixedArray([18446744073709551615], shape=(1,), bits=65, int_bits=65)
APyFixedArray.from_float([num], bits=65, int_bits=65) # APyFixedArray([9223372036854775808], shape=(1,), bits=65, int_bits=65)
nparr = np.asarray(num, dtype=np.uint64)
APyFixedArray.from_array(nparr, bits=65, int_bits=65) # APyFixedArray([9223372036854775808], shape=(1,), bits=65, int_bits=65)
```
TODOs:
- [N/A] "closes #0000" is in the body of the PR description to [link the related …
=> Avoid casting Python ints to floats in APyFixedArray.from_*

src/apytypes_mp.cc, src/apytypes_mp.h
=> Rewrite inline shift to only use a single pointer and for-loops

CHANGELOG.md, lib/test/apyfixed/test_methods.py, src/apyfixed_util.h
This PR fixes overflow to infinity when casting `APyFixed*` to float, and thus closes #511.
*This PR is not ready as there is a failing test case. The test intends to check that a fixed-point number can round to infinity. Either there is a case missing when rounding the mantissa (as the exponent does not seem to be updated), or the test case is wrong. Can you take a look @miklhh?*
=> Fix overflow in fixed-point to float conversion

CHANGELOG.md, docs/api/apyfloat.rst, lib/apytypes/_apytypes.pyi, lib/test/apyfloat/test_methods.py, src/apyfloat.cc, src/apyfloat.h, src/apyfloat_wrapper.cc
This PR adds the convenience methods `inf` and `nan` to `APyFloat`, making it simple to create infinity and NaN of a given format. 
=> Add convenience methods 'inf' and 'nan' for APyFloat

CHANGELOG.md, lib/test/apyfloat/test_arithmetic.py, lib/test/apyfloat/test_rounding.py, src/apyfloat_util.h
Fix bug in floating-point addition/subtraction that occurred when the exponent difference was larger or equal to 64.
It was found by running the Berkeley TestFloat script. From using `git bisect`, it was introduced in ae53f0b but didn't trigger any test cases. New test cases have therefore been added. 
=> Fix bug in APyFloat add/sub

lib/apytypes/_apytypes.pyi, lib/test/apyfloatarray/test_representation.py, src/apyarray.h, src/apyfloatarray_wrapper.cc
=> docs: remove redundant `to_numpy()` from APyFloatArray examples

CHANGELOG.md, lib/test/apyfixedarray/test_methods.py, src/apycfixed.cc, src/apycfixedarray.cc, src/apyfixed.cc, src/apyfixed_util.h, src/apyfixedarray.cc, src/apyfloat_util.h
This PR makes the unsafe (fast-path) fixed-point casting function explicit by renaming it `fixed_point_cast_unsafe`. This PR also introduces a safe fixed-point casting function `fixed_point_cast` that can be used safely at any time.
Closes #683.
=> src: make unsafe fixed-point casting explicit

lib/test/apycfixed/test_constructors.py, lib/test/apycfloat/test_constructors.py, src/apycfixed.cc, src/apycfloat.cc, src/apyfixedarray.cc, src/python_util.h
Support some more Numpy types when constructing APyTypes types.
Closes #706
=> src: support more Numpy types during construction

meson.build
Closes #709 
```
apytypes 0.4.0.dev25+gc99152b7.d20250609
Subprojects
fmt         : YES
highway     : YES
nanobind    : YES
robin-map   : YES (from nanobind)
User defined options
Native files: /tmp/apytypes/.mesonpy-za2_7xts/meson-python-native-file.ini
--->  b_ndebug    : if-release
b_vscrt     : md
buildtype   : release
```
=> build: add option `b_ndebug=if-release`

.github/workflows/tests-debug-memcheck.yml, lib/test/apyfixed/test_constructors.py, src/apycfixed.cc, src/apycfixed.h, src/apycfixedarray.cc, src/apycfixedarray.h, src/apyfixed.cc, src/apyfixed.h, src/apyfixed_util.h, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfloat.h, src/apyfloatarray.cc, src/apyfloatarray.h, src/apytypes_scratch_vector.h, src/ieee754.h
Bring back the performance when constructing fixed points from floating points.
Closes #712
=> src: specialize `fixed_point_from_double()` for single limbs

CHANGELOG.md, examples/ode_solver.py, lib/test/test_contextmanagers.py, src/apytypes_common.cc
Added new floating-point example, studying word-length effects in an ODE solver. The example is inspired from [this](https://royalsocietypublishing.org/doi/10.1098/rsos.211631) article. 
The code is similar to the example for vector rotation, but it's a fun example for floating-point people.
I also modified `APyFloatQuantizationContext` to allow the seed parameter for all quantization modes (not only stochastic ones). This simplified iterating over the same function using different modes while using a specific seed.
=> Example: Floating-point ODE solver

CHANGELOG.md, lib/apytypes/_apytypes.pyi, lib/apytypes/_utils.py, lib/test/apyfloatarray/test_methods.py, src/apycfixedarray.cc, src/apycfixedarray.h, src/apycfixedarray_wrapper.cc, src/apycfloat_wrapper.cc, src/apycfloatarray.cc, src/apycfloatarray.h, src/apycfloatarray_wrapper.cc, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_wrapper.cc, src/python_util.h
This PR changes the [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) semantics of APyTypes' initializers to [Iterable](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable). This is because the Numpy arrays are considered Iterable, but not of Sequence type.
=> src: Iterable in favor of Sequence

src/apyfixed.h, src/apyfloat.cc, src/apyfloat_util.h, src/apytypes_util.h
This PR should speed up the general (long) floating-point multiplication routine somewhat. I wrote a Mandelbrot set renderer, and this change had a small but noticeable impact on it.
=> src: remove `to_double()` casts from apyfloat_util.h

examples/approximate_multiplication.py, examples/ode_solver.py
New example: plot the error of an approximate E4M3 multiplication. 
`.to_numpy()` is used before plotting at the moment, see issue #769.
=> Add example for approximate floating-point multiplication

CHANGELOG.md, examples/approximate_multiplication.py, lib/apytypes/_apytypes.pyi, lib/test/apyfixedarray/test_methods.py, lib/test/apyfloatarray/test_methods.py, src/apyarray.h, src/apycfixedarray.cc, src/apycfixedarray.h, src/apycfixedarray_wrapper.cc, src/apycfloatarray.cc, src/apycfloatarray.h, src/apycfloatarray_wrapper.cc, src/apyfixedarray.cc, src/apyfixedarray.h, src/apyfixedarray_wrapper.cc, src/apyfloatarray.cc, src/apyfloatarray.h, src/apyfloatarray_wrapper.cc
Closes #777 and starts solving #769.
An exception is thrown if `copy=False` is passed, `copy=None` and `copy=True` are fine.
The `dtype` parameter is currently ignored and  `np.float64`/`np.complex128` is always returned.
NumPy seems to check the type afterwards and cast it if needed. I think this is fine, at least for now. Letting NumPy cast types automatically (if needed) will make APyTypes play more nicely with other libraries, although these conversions aren't exactly correct. 
I also removed the `.to_numpy()` from the example of approximate FP multiplication, PR #776.
=> Handle dtype and copy arguments in __array__
